### ISSUE TITLE
File size in MB

### ISSUE THREAD

**Issue by MohammedAlaaMorsi** [bosphere/Android-FileLogger#2]
What should I put in maxTotalSize(long maxSize) if I want the max file size to be 1MB ?

**Comment by MohammedAlaaMorsi** [comment]
I found the solution it will be  1 * 1024 * 1024  // 1mb

**Comment by MohammedAlaaMorsi** [comment]
What is happening when file reach maxTotalSize does it stop writing logs to the file or it override the existing log data ?

**Comment by bosphere** [comment]
when doing housekeeping, log files will be deleted in order to meet the size requirement
