### ISSUE TITLE
Logging not working

### ISSUE THREAD

**Issue by MohammedAlaaMorsi** [bosphere/Android-FileLogger#3]
when I enable logging for first time it writes log to the file but if I close the application and open it again it not continue writing to the file

**Comment by bosphere** [comment]
Please provide sample project or code snippet to reproduce this issue.

**Comment by MohammedAlaaMorsi** [comment]
Sorry I can't share my code ,I solved this issue by init() the FL  every time my application starts on login page

**Comment by bosphere** [comment]
`FL.init()` should be called only once upon app launch. The recommended approach is to create your own `Application` subclass and do your one-time initialisation steps under its `onCreate()` callback.

Anyways, closing this issue as nothing to be done in the scope of this project.
