### ISSUE TITLE
Does not support write to same file from different apps

### ISSUE THREAD

**Issue by iBog** [bosphere/Android-FileLogger#7]
I have group of apps with different functions, which user should use simultaneously, switching from one to another and back, apps are using FileLogger.
Current Android-FileLogger implementation works incorrectly when apps write to the same file called for example "15_06_2018.txt", which created as a combined log for this day.

**Comment by bosphere** [comment]
Restricted by the current design, multi-process usage is not supported. To achieve what you want, you should elect one app as the master and write the logs to file from only the master. Other apps that run in different processes should communicate with the master app to write the logs they want.
