### ISSUE TITLE
Control over flush

### ISSUE THREAD

**Issue by gmuellercole** [bosphere/Android-FileLogger#8]
When a burst of logs is received, the FileLoggerService will dequeue the logs and after 2 seconds of no new messages, the log will be flushed to file. 

I have a concern about a unhandled exception that causes an app to crash. At present, I am installing a uncaught exception handler. The UEH will log the exception and then it does a Thread.sleep(2100) in the hope that the log will be written. 

That's kinda tenuous. I was thinking that if an error is logged (as opposed to other level) that the flush could be accelerated. Perhaps a config value to specify the max time allowed between the log of an error and the commence of flush. An alternative would be to surface a method allowing the caller to force flush.

**Comment by bosphere** [comment]
Thanks for the feedback. It was in fact considered in my original design that logging of an exception shall trigger flushing immediately, however I missed this in my implementation. I'll put up a fix for it.

**Comment by bosphere** [comment]
It's fixed in v1.0.6
